#!/bin/bash

set -o errexit
set -o xtrace
set -o nounset

# The first argument is the location of the reads in the container filesystem.
# The will be present in a read-only directory
READS="$@"

# The assembly should be written to the file "contigs.fa" in the output directory
OUTPUT=/bbx/output

TMP_DIR=`mktemp -d`
cd ${TMP_DIR}

# CPUs available
CPU=$(nproc)

# Create shuffled fastq file from paired ends
FASTQ=$(mktemp)
zcat ${READS} | fastq_to_fasta -Q33 | paste - - | shuf | sed 's/\t/\n/' > ${FASTQ}

GAP_VALUE=15
LOAD_SKG=0
GENOME_SIZE=60000000

SparseAssembler g ${GAP_VALUE} k ${KMER_SIZE} LD ${LOAD_SKG} GS ${GENOME_SIZE} NodeCovTh ${NODE_COVERAGE_THRESHOLD} EdgeCovTh ${EDGE_COVERAGE_THRESHOLD} PathCovTh ${PATH_COVERAGE_THRESHOLD} f ${FASTQ}

mv Contigs.txt ${OUTPUT}
